### ISSUE TITLE
How can i call the get_token.py in HomeAssistant (hassio)?

### ISSUE THREAD

**Issue by Flop2006** [sermayoral/ha-samsungtv-encrypted#2]
Is there a way to call the get_token.py script via HomeAssistant (hassio)?
As far as i see there is no command line.

**Comment by sermayoral** [comment]
Hi @Flop2006 

As I know, you can't do it in Hass.io.

Please, do it in any PC or Laptop connected to your LAN. You only need to install Python 3.

**Comment by Flop2006** [comment]
I found out there's a command line in hassio.
You can use "File Editor" and then on the gear wheel in the upper right corner.
Here there is an entry "Execute shell command"

But when I call ``python3 custom_components/samsungtv_encrypted/get_token.py --ip 192.168.2.25 --port 8080`` the following error message appears:

`Command executed: python3 custom_components/samsungtv_encrypted/get_token.py --ip 192.168.2.25 --port 8080: 1
Traceback (most recent call last):
  File "custom_components/samsungtv_encrypted/get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "/config/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "/config/custom_components/samsungtv_encrypted/PySmartCrypto/crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'`

**Comment by sermayoral** [comment]
The module Crypto.Cipher is not installed in the Hass.io environment. 

try: pip3 install Crypto.Cipher (or pip install Crypto.Cipher)

But I suppose you cannot install anything in Hass.io (its a closed system).

If you have no alternative to Hass.io and the above does not work for you, you can try installing [AppDaemon4](https://github.com/hassio-addons/addon-appdaemon/blob/master/README.md) specifying in the configuration:
```
python_packages:
  - Crypto.Cipher
```
It's a full python environment for Hass.io. I have not tried yet, but it sounds good.

Luck!

**Comment by Flop2006** [comment]
With `pip3 install Crypto.Cipher` i got 
```
Command executed: pip3 install Crypto.Cipher: 1
ERROR: Could not find a version that satisfies the requirement Crypto.Cipher (from versions: none)
ERROR: No matching distribution found for Crypto.Cipher
```
I guess it is not the name of the package, so i try `pip install Crypto` via the AppDeamon4.

Now the package "Crypto 1.4.1" is installed, I can see it also via "Execute shell command", but the Error Message is the same:

```
Command executed: python3 custom_components/samsungtv_encrypted/get_token.py --ip 192.168.2.25 --port 8080: 1
Traceback (most recent call last):
  File "custom_components/samsungtv_encrypted/get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "/config/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "/config/custom_components/samsungtv_encrypted/PySmartCrypto/crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```
I guess without this, the whole programm did not work?

**Comment by t151602** [comment]
> With `pip3 install Crypto.Cipher` i got
> 
> ```
> Command executed: pip3 install Crypto.Cipher: 1
> ERROR: Could not find a version that satisfies the requirement Crypto.Cipher (from versions: none)
> ERROR: No matching distribution found for Crypto.Cipher
> ```
> 
> I guess it is not the name of the package, so i try `pip install Crypto` via the AppDeamon4.
> 
> Now the package "Crypto 1.4.1" is installed, I can see it also via "Execute shell command", but the Error Message is the same:
> 
> ```
> Command executed: python3 custom_components/samsungtv_encrypted/get_token.py --ip 192.168.2.25 --port 8080: 1
> Traceback (most recent call last):
>   File "custom_components/samsungtv_encrypted/get_token.py", line 3, in <module>
>     from PySmartCrypto.pysmartcrypto import PySmartCrypto
>   File "/config/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
>     from . import crypto
>   File "/config/custom_components/samsungtv_encrypted/PySmartCrypto/crypto.py", line 2, in <module>
>     from Crypto.Cipher import AES
> ModuleNotFoundError: No module named 'Crypto'
> ```
> 
> I guess without this, the whole programm did not work?

Sorry. The package name is PyCrypto: https://pypi.org/project/pycrypto/

**Comment by Flop2006** [comment]
Thanks!
Next error with pip install PyCrypto is:

```
    running build_ext
    running build_configure
    checking for gcc... no
    checking for cc... no
    checking for cl.exe... no
    configure: error: in `/tmp/pip-install-wz9d74za/pycrypto':
    configure: error: no acceptable C compiler found in $PATH
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wz9d74za/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-wz9d74za/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-wz9d74za/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wz9d74za/pycrypto/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wz9d74za/pycrypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7kdnvd7p/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[18:43:12] FATAL: Failed installing package pycrypto
[cont-init.d] appdaemon.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
```
Which packages are still missing?
gcc?

**Comment by sermayoral** [comment]
@Flop2006 AppDaemon seems not to find gcc. I suppose PyCrypto needs it for something.

I'm not familiar with AppDaemon, but surfing the Internet i found you could tell AppDaemon to use gcc:
```
  "log_level": "info",
  "system_packages": [
    "libcurl",
    "python3-dev",
    "curl-dev",
    "gcc",
    "g++"
  ],
  "python_packages": [
    "pip==19.0.2",
    "pycurl"
  ]
}
```
As said before, I would use a normal PC with a Python environment to get the token and sessionid of your TV. You only have to do this once. After that, you don't need to execute get_token.py anymore. I'm not sure if you are going to get this working on AppDaemon4. Maybe or maybe not. Lucks.

Remember execute de get_tokey.py with the TV turned on and connected to Internet using the IP specified in the argument of the command. TV will show you a 4-digit PIN in the screen

**Comment by Flop2006** [comment]
The installation of pyCrypto in Appdaemon4 works with
```
system_packages:
  - python3-dev
  - curl-dev
  - gcc
  - musl
  - g++
python_packages:
  - PyCrypto
init_commands:
  - >-
    python3 /config/custom_components/samsungtv_encrypted/get_token.py --ip
    192.168.2.25 --port 8080
```
with the init command i see the code on the tv but i cant insert the pin.
The "Execute shell command" shows still the `ModuleNotFoundError: No module named 'Crypto'` error. So also no possibility to enter the code.

A spare raspberry to which I copied the complete package brings the following error message:
```
python get_token.py --ip     192.168.2.25 --port 8080
Traceback (most recent call last):
  File "get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "/home/pi/pimatic-app/etc/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "/home/pi/pimatic-app/etc/samsungtv_encrypted/PySmartCrypto/crypto.py", line 6, in <module>
    from .py3rijndael.rijndael import Rijndael
ImportError: No module named py3rijndael.rijndael
```
I don't think that's applicable to me.
Maybe someone else can find an easier way directly through hass.io.

**Comment by sermayoral** [comment]
Deprecated Repository

Please re-open your issue (if it already exists) in the new one: https://github.com/sermayoral/ha-samsungtv-encrypted
