### ISSUE TITLE
I just can’t get token

### ISSUE THREAD

**Issue by sashadeg** [sermayoral/ha-samsungtv-encrypted#24]
I’ve been suffering for 3 weeks! Help me please!
Oh my god, Author, make normal use instructions. Here, not all people are python masters.The author sends me this [link](https://github.com/sermayoral/ha-samsungtv-encrypted/issues/5#issuecomment-601482275), but this does not work. It does not even indicate that you need to install additional modules.
I figured out how to do this myself, but still get_token.py does not work for me.

```
C:\Windows\system32>cd C:\ha-samsungtv-encrypted-master\custom_components\samsungtv_encrypted

C:\ha-samsungtv-encrypted-master\custom_components\samsungtv_encrypted>get_token.py --ip 192.168.100.2 --port 8080
Traceback (most recent call last):
  File "C:\ha-samsungtv-encrypted-master\custom_components\samsungtv_encrypted\get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "C:\Users\Professional\Desktop\ha-samsungtv-encrypted-master\custom_components\samsungtv_encrypted\PySmartCrypto\pysmartcrypto.py", line 2, in <module>
  File "C:\Users\Professional\Desktop\ha-samsungtv-encrypted-master\custom_components\samsungtv_encrypted\PySmartCrypto\crypto.py", line 2, in <module>
ImportError: No module named Crypto.Cipher
```

**Comment by sermayoral** [comment]
@sashadeg sorry, the smartcrypto module is not mine. We have use the module SmartCrypto from https://github.com/eclair4151/SmartCrypto, and I use his instructions (not mine). 

Everything I can tell you, try:

```
pip3 install pycrypto
```

After that, you could execute the get_token.py
