### ISSUE TITLE
EUJ8000 trying to get token

### ISSUE THREAD

**Issue by Sildenafil99** [sermayoral/ha-samsungtv-encrypted#30]
I'm trying to get token but i have:
python3 get_token.py --ip 192.168.1.101 --port 8080
Traceback (most recent call last):
  File "get_token.py", line 27, in <module>
    main(sys.argv[1:])
  File "get_token.py", line 24, in main
    PySmartCrypto(ip, port)
  File "/home/gianni/Scrivania/samsung/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 123, in __init__
    self._connection = self.connect()
  File "/home/gianni/Scrivania/samsung/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 99, in connect
    connection = websocket.create_connection(websocket_url)
AttributeError: module 'websocket' has no attribute 'create_connection'

**Comment by Sildenafil99** [comment]
sorry, i have installed wrong pip websocket

**Comment by Sildenafil99** [comment]
Ok, tested on UE55JS8000TXZT and don't work

**Comment by sermayoral** [comment]
@Sildenafil99 

Ok, I will update README with your TV model as 'not working models'

Sorry.
