### ISSUE TITLE
Get token - Crypto module not found

### ISSUE THREAD

**Issue by homected** [sermayoral/ha-samsungtv-encrypted#36]
I tried the command from Ubuntu and FreeBSD: python3 get_token.py --ip 192.168.3.23 --port 8080

but in both cases I get this error:

Traceback (most recent call last):
  File "get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "/home/jlgalindo/Documents/samsung/ha-samsungtv-encrypted/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "/home/jlgalindo/Documents/samsung/ha-samsungtv-encrypted/custom_components/samsungtv_encrypted/PySmartCrypto/crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by homected** [comment]
Finally with these commands I solve the error:

python3 -m pip install pycrypto
python3 -m pip install websocket
python3 -m pip install websocket-client
