### ISSUE TITLE
Crypto Cipher problem

### ISSUE THREAD

**Issue by privatesam** [sermayoral/ha-samsungtv-encrypted#54]
Getting the following problem:

`.homeassistant/custom_components/samsungtv_encrypted$ python ./get_token.py -ip 10.7.7.58 -port 8080
Traceback (most recent call last):
  File "./get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_encrypted/PySmartCrypto/crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
`

**Comment by ChaoticBD** [comment]
Have the same issue running python3 by hassio ssh addon
---
add - that was a bad idea to run this in ha ssh addon. 
To run it via ssh i installed python3, pip, websocket, requests and crypto... may be running from hassio scripts will be more clean and easy

**Comment by estevez-dev** [comment]
```
pip install pycrypto
```
If you already have `crypto` installed:
```
pip uninstall crypto
pip uninstall pycrypto
pip install pycrypto
```

**Comment by alparo** [comment]
For me helped running the script explicitly with python 3:
python3 get_token.py
