### ISSUE TITLE
get_token.py

### ISSUE THREAD

**Issue by jmrocha88** [sermayoral/ha-samsungtv-encrypted#86]
i tried to take token for my tv (UE50JU6900) but i recived this:

C:\Users\José Rocha\Desktop\samsungtv_encrypted>get_token.py --ip 192.168.68.61 --port 8080
Traceback (most recent call last):
  File "C:\Users\José Rocha\Desktop\samsungtv_encrypted\get_token.py", line 4, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "C:\Users\José Rocha\Desktop\samsungtv_encrypted\PySmartCrypto\pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "C:\Users\José Rocha\Desktop\samsungtv_encrypted\PySmartCrypto\crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

can you help me?

**Comment by Will695** [comment]
you need to put py infront of get_token.py and have python installed.
py get_token.py --ip 192.168.68.61 --port 8080

**Comment by ende0** [comment]
Can someone help me with this, getting the same error..

**Comment by yeomos** [comment]
you need to have some python modules installed.
pycryptodome, requests and websocket-client 
So 

>pip install pycryptodome
>pip install requests
>pip install websocket-client
>py get_token.py --ip xxx.xxx.xxx.xxx --port 8080

**Comment by ende0** [comment]
I've done this in Windows and it worked, but it didn't created the TOKEN and SESSION_ID file's or text somewhere.. Do I have to do this inside the terminal of HA?
